### ISSUE TITLE
Changing solar PV FLH does not update households, buildings and hydrogen solar PV production (when leaving the installed capacity-related sliders untouched)

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3002]
Follow-up on https://github.com/quintel/etmodel/issues/2906:

The previous issue was fixed for wind turbines by storing the original number of units in the input statement before updating the FLH and afterwards calculating the new production based on the updated FLH and the original number of units. This also works for updating the production for solar PV parcs but doesn't work for `energy_hydrogen_solar_pv_solar_radiation`, `buildings_solar_pv_solar_radiation`, and `households_solar_pv_solar_radiation` since these nodes are not included in the `preset_demand` group (which is why the number of units cannot be calculated at the start of the [input statement for the FLH of solar PV](https://github.com/quintel/etsource/blob/master/inputs/full_load_hours/flh_of_solar_pv_solar_radiation.ad).

In order to fix this issue we should find a workaround for storing the original number of units for the producer nodes mentioned above. @antw do you know why the sandbox does allow us to query the number of units but a query at the start of the input statement doesn't? Does that have to do with the fact that not all nodes in the graph have been calculated yet at the time the input statement is executed?

![Screen Shot 2019-03-12 at 14 58 35](https://user-images.githubusercontent.com/5946498/54213933-8e78ed00-44e5-11e9-9e98-c2130db03479.png)

**Edit**: The previous issue hasn't been fixed for [`flh_of_energy_hydrogen_wind_turbine_offshore`](https://github.com/quintel/etsource/blob/master/inputs/full_load_hours/flh_of_energy_hydrogen_wind_turbine_offshore.ad), since [`energy_hydrogen_wind_turbine_offshore`](https://github.com/quintel/etsource/blob/master/nodes/energy/energy_hydrogen_wind_turbine_offshore.central_producer.ad) isn't part of the `preset_demand` group either.

**Comment by redekok** [comment]
@ChaelKruip, @michieldenhaan, @marliekeverweij and I just had a short meeting about this issue and some (more specific) questions arose:

1. What is the reason for the fact that the NoU (in the present year) can't be queried at the the start of the input statement? Does that have to do with the fact that not all nodes in the graph have been calculated yet at the time the input statement is executed?

2. How are the demand and FLH values from the [central_producers.csv](https://github.com/quintel/etsource/blob/master/datasets/nl/central_producers.csv) queried for converters? When a converter is in a certain group (for example, the preset_demand or central_producers group), this is done implicitly, isn't it? What exactly happens in the engine in these situations? 

3. For other converters (for example, [`energy_hydrogen_electrolysis_wind_electricity`](energy_hydrogen_electrolysis_wind_electricity), these values are queried by `~ demand = CENTRAL_PRODUCTION(name_of_converter, demand)` and `~ full_load_hours = CENTRAL_PRODUCTION(name_of_converter, full_load_hours)`. Do you know if we can use such queries in input statements as well?

4. What exactly is the influence of the `priority = 1` line of code in an [input statement](https://github.com/quintel/etsource/blob/master/inputs/full_load_hours/flh_of_solar_pv_solar_radiation.ad#L16)? Would it be a possibility to lower the priority value for this input statement in order to calculate the demand for the relevant nodes first (before updating the input statements)?

@antw We were wondering if you have any answers to these questions?

**Comment by antw** [comment]
> 1. What is the reason for the fact that the NoU (in the present year) can't be queried at the the start of the input statement? Does that have to do with the fact that not all nodes in the graph have been calculated yet at the time the input statement is executed?

The number of units is probably calculated by ETEngine or Merit, based on the capacity, full load hours, and demand of the node. If the demand is not yet known (because the graph has not been calculated when inputs are run), then the NoU will not be available.

> 2. How are the demand and FLH values from the central_producers.csv queried for converters? When a converter is in a certain group (for example, the preset_demand or central_producers group), this is done implicitly, isn't it? What exactly happens in the engine in these situations?

The central_producers.csv file is used by Atlas+Refinery, but not by ETEngine. I believe the full_load_hours from the CSV *are* kept and used by ETEngine, but demand is not. The only time demand is carried over from Atlas+Refinery to ETEngine is when a node belongs to the preset_demand group; only these nodes have a demand which can be read while running inputs.

> 3. [...] Do you know if we can use such queries in input statements as well?

`CENTRAL_PRODUCTION` is currently only available in Atlas+Refinery.

> 4. What exactly is the influence of the `priority = 1` line of code in an input statement? 

The priority controls the order in which inputs are executed. For example, if the values set by input A might influence input B, we would set input A to have a higher priority to ensure it is executed first.

> 4. Would it be a possibility to lower the priority value for this input statement in order to calculate the demand for the relevant nodes first (before updating the input statements)?

I don't think this would work. Setting the FLH after the graph has been calculated (which includes Merit, Fever, Hydrogen) will be too late: the graph (and the merit order) will have been calculated with the old FLH.

**Comment by michieldenhaan** [comment]
Is this issue still relevant @redekok? It looks like PV production of households, buildings and H2 is updated when changing the FLH slider

**Comment by marliekeverweij** [comment]
A miracle has happened!  ✨  Somehow this issue is fixed. Who has a clue what fixed the issue? The merit order calculation has been updated lately right?

**Comment by redekok** [comment]
It doesn't seem to be fixed for solar PV on rooftops, does it? When I leave the shares of solar PV on rooftops untouched and first change the # FLH for solar PV, the energy production stays the same (on BETA).

**Comment by marliekeverweij** [comment]
Yes you are right! That's the issue. _Te vroeg gejuicht......_

**Comment by redekok** [comment]
Haha, too bad.. So to conclude: yes, unfortunately this issue is still relevant @michieldenhaan.. :(

**Comment by marliekeverweij** [comment]
Shall we change the title of the issue since it only happens when users do not change the installed solar pv capacity in their scenario? And this does almost never happens :) 

(I'll put the label 'minor' on the this issue)

**Comment by redekok** [comment]
I've changed the title of the issue. Feel free to rename the issue if you have a better suggestion. And @marliekeverweij, do you think we could remove the `on hold` label again?

**Comment by kaskranenburgQ** [comment]
In [PV curtailment quintel/etsource#3200](https://github.com/quintel/etsource/pull/3200) we solved this issue for all solar production nodes that have been added to the preset_demand group. 
This issue still persists for the energy_hydrogen_solar_pv_solar_radiation node.

**Comment by kndehaan** [comment]
Fixed with https://github.com/quintel/etsource/pull/3221
